### ISSUE TITLE
Using apollo vscode plugin shows error

### ISSUE THREAD

**Issue by mwarger** [ahrnee/graphql-codegen-hasura#10]
The apollo vscode plugin crashes because there is more than one version of every graphql document created when generating code.

`Error initializing Apollo GraphQL project "graphql": Error: ️️There are multiple definitions for the `queryTodoById` operation. Please rename or remove all operations with the duplicated name before continuing.`

I believe this is due to the `index.ts` file being generated by the hasura plugin, and then the typescript code generators picking up this file and generating their respective documents from it.

I'm not sure if it was intended to be used with the vscode plugin, but I think it would be a great help if the actual name was not duplicated.

**Comment by ahrnee** [comment]
Hi @mwarger 

This is a side-effect of leveraging graphql-code-generator to generate the base types (which includes a gql duplication step).

You should be able to use a [config file for the Apollo VSCode Plugin](https://www.apollographql.com/docs/devtools/apollo-config/) to ignore the duplicate set of gql definitions. As an example, here is the one I use:

```
// apollo.config.js
module.exports = {
  client: {
    excludes: ["src/gql/noref/**/*"],
    service: {
      name: "csee",
      localSchemaFile: "./schema/graphql.schema.json"
    }
  }
};
```

A future enhancement to this library could be to replace the graphql-code-generator step with custom base type code generation, which would negate this issue.

**Comment by mwarger** [comment]
Thank you! I did not see that the Apollo config had that option.
