### ISSUE TITLE
[Question] Where to get ApolloProvider

### ISSUE THREAD

**Issue by scheung38** [ahrnee/graphql-codegen-hasura#11]
import { ApolloProvider } from '@apollo/react-hooks';
import { ApolloProvider } from '@apollo/react-components';

 But it says:

Please note that as of version 4.0.0 you should prefer to import React hooks and testing utilities from @apollo/client

So where should I get ApolloProvider from?

**Comment by ahrnee** [comment]
Hi @scheung38 - where are you seeing this message? I my own usage I have been importing from : 
`import { ApolloProvider } from '@apollo/react-hooks';`

However, I believe you can also import from: 
`import { ApolloProvider } from '@apollo/client';`

**Comment by scheung38** [comment]
Hi which one to take?

**Comment by GollyJer** [comment]
> But it says:
> Please note that as of version 4.0.0 you should prefer to **import** React hooks and testing utilities **from @apollo/client**

They are telling you the answer. ---------------------------------👆------------------------------------------------👆
