### ISSUE TITLE
Problem where there's not id field

### ISSUE THREAD

**Issue by pakokrew** [ahrnee/graphql-codegen-hasura#13]
By trying to use your package in our project, I've spotted that the generation fails when tables doesn't have an `id` field. 

Here's the error I get

```
    TypeError: Cannot read property 'name' of undefined
        at Object.exports.ID_FIELD_TEST (/Users/pac/dev/metagame/TheGame/node_modules/graphql-codegen
-hasura-shared/utils.js:8:14)
        at Object.getIdPostGresFieldType (/Users/pac/dev/metagame/TheGame/node_modules/graphql-codege
n-hasura-shared/utils.js:59:20)
        at makeFetchObjectsGQL (/Users/pac/dev/metagame/TheGame/node_modules/graphql-codegen-hasura-s
hared/gqlInjectors.js:84:46)
        at Object.injectFetchAsQueryGql (/Users/pac/dev/metagame/TheGame/node_modules/graphql-codegen
-hasura-shared/gqlInjectors.js:39:7)
        at injectEntityFetchAsQueryGql (/Users/pac/dev/metagame/TheGame/node_modules/graphql-codegen-
hasura-gql/index.js:52:37)
        at /Users/pac/dev/metagame/TheGame/node_modules/graphql-codegen-hasura-gql/index.js:23:31
```

Here's our project&settings
https://github.com/MetaFam/TheGame/blob/codegen/packages/graphql-codegen/graphql-codegen-gql.yaml

**Comment by ahrnee** [comment]
@pakokrew - I have looked into this and don't have a straight forward fix. The primary issue is that I don't know of a way to determine a primary key from a GQL schema (and FieldDefinitionNodes). As such, I rely on the name of the primary key field being 'id'. 

For now I am going to update the documentation to indicate that an id field is a requirement and limitation. 

If you, or anyone else, knows how to identify a primary key field from the GQL schema, let me know, or submit a pull request with the fix. The relevant section of code is [here](https://github.com/ahrnee/graphql-codegen-hasura/blob/fbbb449ad5e4155dbc0b2cc7955712695d7d86a8/packages/graphql-codegen-hasura-shared/src/utils.ts#L78).

**Comment by ahrnee** [comment]
@pakokrew - further to the above comment. I have updated the code so that it will successfully build if it encounters a table without an id fields. However, it will only generate a QueryByObjects method. Most of the other methods rely on an id field, and will be omitted (for those table only).

I will close this issue, and add the above comments to the documentation as limitations.

**Comment by pakokrew** [comment]
Already a good thing that the code builds, thank you very much. 

In my cases, the tables without an 'id' field are tables with many-to-many relationships, so I don't really need to query them by primary key. 

That will solve the problem for most of the cases I think!

**Comment by ahrnee** [comment]
@pakokrew - good, glad this will sort your issue. The package is published now.
